Carros = [
    {'id': 1, 'marca': 'Fiat', 'modelo': 'Marea', 'ano': 1999},
    {'id': 2, 'marca': 'Chevrolet', 'modelo': 'Onix', 'ano': 2020},
    {'id': 3, 'marca': 'Volkswagen', 'modelo': 'Gol', 'ano': 2012},
    {'id': 4, 'marca': 'Toyota', 'modelo': 'Corolla', 'ano': 2018},
    {'id': 5, 'marca': 'Honda', 'modelo': 'Civic', 'ano': 2015},
    {'id': 6, 'marca': 'Ford', 'modelo': 'Ka', 'ano': 2014},
    {'id': 7, 'marca': 'Renault', 'modelo': 'Sandero', 'ano': 2016},
    {'id': 8, 'marca': 'Hyundai', 'modelo': 'HB20', 'ano': 2019},
    {'id': 9, 'marca': 'Peugeot', 'modelo': '208', 'ano': 2021},
    {'id': 10, 'marca': 'Nissan', 'modelo': 'Versa', 'ano': 2017},
    {'id': 11, 'marca': 'Jeep', 'modelo': 'Renegade', 'ano': 2022},
    {'id': 12, 'marca': 'Kia', 'modelo': 'Cerato', 'ano': 2013},
    {'id': 13, 'marca': 'BMW', 'modelo': '320i', 'ano': 2016},
    {'id': 14, 'marca': 'Mercedes-Benz', 'modelo': 'C180', 'ano': 2017},
    {'id': 15, 'marca': 'Audi', 'modelo': 'A3', 'ano': 2018},
    {'id': 16, 'marca': 'Mitsubishi', 'modelo': 'Lancer', 'ano': 2015},
    {'id': 17, 'marca': 'Subaru', 'modelo': 'Impreza', 'ano': 2014},
    {'id': 18, 'marca': 'Citroën', 'modelo': 'C3', 'ano': 2019},
    {'id': 19, 'marca': 'Chery', 'modelo': 'Tiggo 5X', 'ano': 2020},
    {'id': 20, 'marca': 'Lifan', 'modelo': 'X60', 'ano': 2018},
    {'id': 21, 'marca': 'Volvo', 'modelo': 'XC60', 'ano': 2021},
    {'id': 22, 'marca': 'Land Rover', 'modelo': 'Evoque', 'ano': 2019},
    {'id': 23, 'marca': 'Porsche', 'modelo': 'Cayenne', 'ano': 2017},
    {'id': 24, 'marca': 'Jaguar', 'modelo': 'XE', 'ano': 2020},
    {'id': 25, 'marca': 'Tesla', 'modelo': 'Model 3', 'ano': 2022},
    {'id': 26, 'marca': 'Chevrolet', 'modelo': 'Cruze', 'ano': 2017},
    {'id': 27, 'marca': 'Volkswagen', 'modelo': 'Virtus', 'ano': 2019},
    {'id': 28, 'marca': 'Toyota', 'modelo': 'Yaris', 'ano': 2018},
    {'id': 29, 'marca': 'Honda', 'modelo': 'Fit', 'ano': 2016},
    {'id': 30, 'marca': 'Ford', 'modelo': 'Fiesta', 'ano': 2015},
    {'id': 31, 'marca': 'Renault', 'modelo': 'Logan', 'ano': 2014},
    {'id': 32, 'marca': 'Hyundai', 'modelo': 'Creta', 'ano': 2020},
    {'id': 33, 'marca': 'Peugeot', 'modelo': '2008', 'ano': 2017},
    {'id': 34, 'marca': 'Nissan', 'modelo': 'Kicks', 'ano': 2021},
    {'id': 35, 'marca': 'Jeep', 'modelo': 'Compass', 'ano': 2021},
    {'id': 36, 'marca': 'Kia', 'modelo': 'Sportage', 'ano': 2019},
    {'id': 37, 'marca': 'BMW', 'modelo': 'X1', 'ano': 2018},
    {'id': 38, 'marca': 'Mercedes-Benz', 'modelo': 'GLA', 'ano': 2019},
    {'id': 39, 'marca': 'Audi', 'modelo': 'Q3', 'ano': 2020},
    {'id': 40, 'marca': 'Mitsubishi', 'modelo': 'ASX', 'ano': 2017},
    {'id': 41, 'marca': 'Subaru', 'modelo': 'Forester', 'ano': 2018},
    {'id': 42, 'marca': 'Citroën', 'modelo': 'Aircross', 'ano': 2015},
    {'id': 43, 'marca': 'Chery', 'modelo': 'QQ', 'ano': 2014},
    {'id': 44, 'marca': 'Lifan', 'modelo': '530', 'ano': 2016},
    {'id': 45, 'marca': 'Volvo', 'modelo': 'S60', 'ano': 2021},
    {'id': 46, 'marca': 'Land Rover', 'modelo': 'Discovery', 'ano': 2019},
    {'id': 47, 'marca': 'Porsche', 'modelo': '911', 'ano': 2022},
    {'id': 48, 'marca': 'Jaguar', 'modelo': 'F-Pace', 'ano': 2021},
    {'id': 49, 'marca': 'Tesla', 'modelo': 'Model Y', 'ano': 2023},
    {'id': 50, 'marca': 'Chevrolet', 'modelo': 'Spin', 'ano': 2015}
]
